# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditquestion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editquestion(self):
    # Test name: edit_question
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/admin/dashboard/")
    # 2 | setWindowSize | 1086x832 | 
    self.driver.set_window_size(1086, 832)
    # 3 | click | xpath=//button[contains(.,'Your Questions')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Your Questions\')]").click()
    # 4 | click | css=.rounded-lg:nth-child(1) .rounded-md:nth-child(2) path:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-lg:nth-child(1) .rounded-md:nth-child(2) path:nth-child(1)").click()
    # 5 | click | name=marks | 
    self.driver.find_element(By.NAME, "marks").click()
    # 6 | type | name=marks | 5
    self.driver.find_element(By.NAME, "marks").send_keys("5")
    # 7 | click | css=.bg-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-primary").click()
    # 8 | close |  | 
    self.driver.close()
  
