# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeletequestion():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deletequestion(self):
    # Test name: delete_question
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://localhost:3000/admin/dashboard/")
    # 2 | setWindowSize | 1084x832 | 
    self.driver.set_window_size(1084, 832)
    # 3 | click | xpath=//button[contains(.,'Your Questions')] | 
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Your Questions\')]").click()
    # 4 | click | xpath=//div[2]/div[3]/div/div | 
    self.driver.find_element(By.XPATH, "//div[2]/div[3]/div/div").click()
    # 5 | close |  | 
    self.driver.close()
  
