# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUsertest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_usertest(self):
    self.driver.get("http://localhost/votesystem/index.php")
    self.driver.set_window_size(1366, 720)
    self.driver.find_element(By.ID, "user_voter").click()
    self.driver.find_element(By.ID, "user_voter").send_keys("3ySU92Gbph4n15x")
    self.driver.find_element(By.ID, "user_password").click()
    self.driver.find_element(By.ID, "user_password").send_keys("1234")
    self.driver.find_element(By.ID, "user_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.XPATH, "//div[@id=\'candidate_list\']/ul/li").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover > .iCheck-helper").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover > .iCheck-helper").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover > .iCheck-helper").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\31 0 .pull-right > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover > .iCheck-helper").click()
    self.driver.find_element(By.ID, "preview").click()
    self.driver.find_element(By.CSS_SELECTOR, "#preview_modal .fa").click()
  
