# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdmintest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_admintest(self):
    self.driver.get("http://localhost/votesystem/admin/index.php")
    self.driver.set_window_size(1366, 720)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("shakti")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("password")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Votes").click()
    self.driver.find_element(By.ID, "voters.php").click()
    self.driver.find_element(By.LINK_TEXT, "New").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) #firstname").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(1) #firstname").send_keys("Aman")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #lastname").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #lastname").send_keys("Dubey")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) #password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) #password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary > .fa-save").click()
    self.driver.find_element(By.CSS_SELECTOR, ".even:nth-child(2) > td:nth-child(4)").click()
    self.driver.find_element(By.ID, "positions.php").click()
    self.driver.find_element(By.CSS_SELECTOR, "#candidates\\.php > span").click()
    self.driver.find_element(By.ID, "ballot.php").click()
    self.driver.find_element(By.ID, "election-title").click()
    self.driver.find_element(By.CSS_SELECTOR, "#config .btn-default").click()
  
