# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignUp():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signUp(self):
    self.driver.get("http://127.0.0.1:3000/SE_Website2/SE/index.html")
    self.driver.set_window_size(787, 816)
    self.driver.find_element(By.ID, "menu-bars").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(1)").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("shailly")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("shaillyyadav979@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".signup-button").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".signup-button").click()
  
