# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.edge.service import Service


class TestAmaz2():
  def setup_method(self, method):
    self.driver = webdriver.Edge(service=Service(r"D:\4th Sem Academics\software engineering\selenium\practise\msedgedriver.exe"))
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_ankit(self):
    self.driver.get("http://127.0.0.1:5500/jaideep/index.html")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.CSS_SELECTOR, "a > img").click()
    self.driver.find_element(By.LINK_TEXT, "Buy Now").click()
    self.driver.find_element(By.CSS_SELECTOR, ".payment-method:nth-child(1) > p").click()
    self.driver.find_element(By.ID, "card-holder-name").click()
    self.driver.find_element(By.ID, "card-holder-name").send_keys("Ajaydeep Rawat")
    self.driver.find_element(By.ID, "card-number").click()
    self.driver.find_element(By.ID, "card-number").send_keys("123456789")
    self.driver.find_element(By.ID, "expiry-date").click()
    self.driver.find_element(By.ID, "expiry-date").send_keys("12/2024")
    self.driver.find_element(By.ID, "cvv").click()
    self.driver.find_element(By.ID, "cvv").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(5)").click()
    self.driver.find_element(By.ID, "card-number").click()
    self.driver.find_element(By.ID, "card-number").send_keys("1234567891111111")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(5)").click()
    self.driver.find_element(By.ID, "cvv").click()
    self.driver.find_element(By.ID, "cvv").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".payment-method:nth-child(2) > p").click()
    self.driver.find_element(By.ID, "bank").click()
    dropdown = self.driver.find_element(By.ID, "bank")
    dropdown.find_element(By.XPATH, "//option[. = 'Bank of Baroda']").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Jaideep Jaiswal")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Dextro@789")
    self.driver.find_element(By.ID, "otp").click()
    self.driver.find_element(By.ID, "otp").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".payment-method:nth-child(3)").click()
    self.driver.find_element(By.ID, "upi-id").click()
    self.driver.find_element(By.ID, "upi-id").send_keys("AnkitGautam@oksbi")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".payment-method:nth-child(4)").click()
    self.driver.find_element(By.ID, "wallet").click()
    dropdown = self.driver.find_element(By.ID, "wallet")
    dropdown.find_element(By.XPATH, "//option[. = 'Venmo']").click()
    self.driver.find_element(By.ID, "wallet-username").click()
    self.driver.find_element(By.ID, "wallet-username").send_keys("ayushgupta.venmo")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-secondary").click()
    self.driver.close()
  
