# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContact():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_contact(self):
    self.driver.get("http://127.0.0.1:3000/SE_Website2/SE/index.html")
    self.driver.set_window_size(791, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(5)").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("Shailly Yadav")
    self.driver.find_element(By.NAME, "email").send_keys("shaillyyadav979@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("123")
    self.driver.find_element(By.NAME, "country").send_keys("India")
    self.driver.find_element(By.NAME, "message").click()
    self.driver.find_element(By.NAME, "message").send_keys("hii")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
    assert self.driver.switch_to.alert.text == "Message sent successfully!"
  
