# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAbout():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_about(self):
    self.driver.get("http://127.0.0.1:3000/SE_Website2/SE/index.html")
    self.driver.set_window_size(792, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(3)").click()
    self.driver.find_element(By.LINK_TEXT, "Start Saving Now").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gsc_col-xs-12:nth-child(1) a").click()
    self.driver.execute_script("window.scrollTo(0,696)")
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, "a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
