# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHome():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_home(self):
    self.driver.get("http://127.0.0.1:3000/SE_Website2/SE/index.html")
    self.driver.set_window_size(787, 816)
    self.driver.find_element(By.ID, "menu-bars").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(2)").click()
    self.driver.find_element(By.ID, "menu-bars").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Get Deals").click()
    self.vars["win8659"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win8659"])
    self.driver.find_element(By.CSS_SELECTOR, ".gsc_col-xs-12:nth-child(1) .title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gsc_col-xs-12:nth-child(1) a").click()
    self.driver.execute_script("window.scrollTo(0,484)")
    self.driver.execute_script("window.scrollTo(0,188)")
  
