# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewPropertyPost():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_newPropertyPost(self):
    self.driver.get("http://localhost:5173/profile")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".title:nth-child(3) button").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("Jeet Royal")
    self.driver.find_element(By.ID, "price").send_keys("35000")
    self.driver.find_element(By.ID, "address").send_keys("Palaj")
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-bold")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".ql-editor").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ql-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>All amenities available</p>'}", element)
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "city").send_keys("Gandhinagar")
    self.driver.find_element(By.ID, "bedroom").click()
    self.driver.find_element(By.ID, "bedroom").click()
    self.driver.find_element(By.ID, "bedroom").send_keys("3")
    self.driver.find_element(By.ID, "bathroom").send_keys("3")
    self.driver.find_element(By.ID, "latitude").click()
    self.driver.find_element(By.ID, "latitude").click()
    element = self.driver.find_element(By.ID, "latitude")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "latitude").send_keys("23.1841")
    self.driver.find_element(By.ID, "longitude").click()
    self.driver.find_element(By.ID, "longitude").send_keys("72.6282")
    self.driver.find_element(By.ID, "size").click()
    self.driver.find_element(By.ID, "size").send_keys("850")
    self.driver.find_element(By.CSS_SELECTOR, ".sendButton").click()
  
