# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Recent Rides").click()
    self.driver.find_element(By.LINK_TEXT, "Settings").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-list-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-list-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-list-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-list-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-list-item:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".sidebar-list-item:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.LINK_TEXT, "Recent Rides").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".recharts-responsive-container:nth-child(2) > .recharts-wrapper > .recharts-surface").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) > .card-inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(3) path").click()
    self.driver.find_element(By.LINK_TEXT, "Recent Rides").click()
  
