# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSavePlace():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_savePlace(self):
    self.driver.get("http://localhost:5173/list?type=buy&city=Gandhinagar&minPrice=0&maxPrice=0")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".imageContainer > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bigImage > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".imgContainer > img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".imgContainer > img")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
