# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test3(self):
    self.driver.get("http://127.0.0.1:5500/dist/index.html")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").send_keys("DHAR")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "searchBar").click()
    self.driver.find_element(By.ID, "searchBar").send_keys("Nagpur")
    self.driver.find_element(By.ID, "search2").click()
    self.driver.find_element(By.ID, "farCel").click()
    self.driver.find_element(By.ID, "farCel").click()
    self.driver.find_element(By.ID, "home").click()
  
