from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

class TestBooking():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_booking(self):
        self.driver.get("http://localhost:3000/login")
        self.driver.set_window_size(1552, 832)
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(1)").send_keys("dharu@gmail.com")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").send_keys("dharu")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar_search").click()
        self.driver.find_element(By.CSS_SELECTOR, "input").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".css-yqxhyq-MuiSvgIcon-root")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("Iconic cities")
        self.driver.find_element(By.CSS_SELECTOR, ".css-yqxhyq-MuiSvgIcon-root").click()
        self.driver.find_element(By.CSS_SELECTOR, "#root > div").click()
        self.driver.find_element(By.CSS_SELECTOR, ".listing-card:nth-child(1) > p:nth-child(4)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(29) > .rdrDayNumber")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".rdrDateDisplayItemActive > input").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(6) > .rdrDayNumber")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".rdrDayHovered > .rdrDayNumber > span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(21) > .rdrDayNumber")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(5)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".rdrDateDisplayItemActive > input").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".rdrDayNumber:nth-child(2) > span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(17) > .rdrDayNumber > span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".rdrDateDisplayItemActive > input").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(6) > .rdrDayNumber > span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".rdrDayHovered > .rdrDayNumber > span").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(27) > .rdrDayNumber")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".rdrDay:nth-child(28)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".button").click()
        self.driver.execute_script("window.scrollTo(0,0)")
        self.driver.find_element(By.CSS_SELECTOR, "#root > div").click()
        self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar_right_account").click()
        self.driver.find_element(By.LINK_TEXT, "Trip List").click()

test = TestBooking()
test.setup_method(None)
test.test_booking()
test.teardown_method(None)

