# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest04():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test04(self):
        self.driver.get("http://127.0.0.1:5500/")
        self.driver.set_window_size(1552, 832)
        self.driver.find_element(By.LINK_TEXT, "Home").click()
        self.driver.find_element(By.LINK_TEXT, "About").click()
        self.driver.find_element(By.LINK_TEXT, "Services").click()
        self.driver.find_element(By.LINK_TEXT, "Pricing").click()
        self.driver.find_element(By.LINK_TEXT, "Book Appointment").click()
        self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "sudhanshuranjan714@gmail.com")
        self.driver.find_element(By.ID, "password").send_keys("Gmail#1234")
