# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest05():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test05(self):
        self.driver.get("http://127.0.0.1:5500/")
        self.driver.set_window_size(1552, 832)
        self.driver.find_element(By.LINK_TEXT, "Book Appointment").click()
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("Sudhanshu Ranjan")
        self.driver.find_element(By.NAME, "email_address").send_keys(
            "202251135@iiitvadodara.ac.in")
        self.driver.find_element(By.NAME, "phone").send_keys("07340427460")
        self.driver.find_element(By.NAME, "date").click()
        self.driver.find_element(By.NAME, "date").send_keys("2024-04-27")
        self.driver.find_element(By.NAME, "message").click()
        self.driver.find_element(By.NAME, "message").send_keys("hello")
        self.driver.find_element(By.CSS_SELECTOR, ".form-btn").click()
        self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("Sudhanshu Ranjan")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(2) > #name").send_keys("202251135@iiitvadodara.ac.in")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(3) > #name").send_keys("07340427460")
        self.driver.find_element(By.ID, "Message").click()
        self.driver.find_element(By.ID, "Message").send_keys(
            "hi i want to have hair styling")
        self.driver.find_element(By.CSS_SELECTOR, ".email-field").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".email-field").send_keys("afd@gmail.com")
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn:nth-child(2) > .span").click()
