# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest01():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test01(self):
        self.driver.get("http://127.0.0.1:5500/")
        self.driver.set_window_size(1552, 832)
        self.driver.find_element(
            By.CSS_SELECTOR, ".btn:nth-child(1) > .span").click()
        self.driver.find_element(By.NAME, "name").click()
        self.driver.find_element(By.NAME, "name").send_keys("Sudhanshu Ranjan")
        self.driver.find_element(By.NAME, "email_address").send_keys(
            "202251135@iiitvadodara.ac.in")
        self.driver.find_element(By.NAME, "phone").send_keys("07340427460")
        self.driver.find_element(By.NAME, "category").click()
        dropdown = self.driver.find_element(By.NAME, "category")
        dropdown.find_element(By.XPATH, "//option[. = 'Beauty & spa']").click()
        self.driver.find_element(By.NAME, "date").click()
        self.driver.find_element(By.NAME, "date").send_keys("2024-04-24")
        self.driver.find_element(By.NAME, "message").click()
        self.driver.find_element(By.NAME, "message").send_keys("welcome")
        self.driver.find_element(By.CSS_SELECTOR, ".form-btn > .span").click()
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "sudhanshuranjan714@gmail.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("Gmail#1234")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
