# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT3():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t3(self):
    # Test name: T3
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:5503/SElogin.html | 
    self.driver.get("http://127.0.0.1:5503/SElogin.html")
    # 2 | setWindowSize | 1119x590 | 
    self.driver.set_window_size(1119, 590)
    # 3 | click | css=.userid | 
    self.driver.find_element(By.CSS_SELECTOR, ".userid").click()
    # 4 | type | css=.userid | sam
    self.driver.find_element(By.CSS_SELECTOR, ".userid").send_keys("sam")
    # 5 | click | css=.password | 
    self.driver.find_element(By.CSS_SELECTOR, ".password").click()
    # 6 | type | css=.password | abdf
    self.driver.find_element(By.CSS_SELECTOR, ".password").send_keys("abdf")
    # 7 | click | css=.login-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    # 8 | click | css=.upload | 
    self.driver.find_element(By.CSS_SELECTOR, ".upload").click()
    # 9 | click | css=.myprofile | 
    self.driver.find_element(By.CSS_SELECTOR, ".myprofile").click()
    # 10 | click | id=selectedSocialMedia | 
    self.driver.find_element(By.ID, "selectedSocialMedia").click()
    # 11 | click | xpath=(//button[@id='selectedSocialMedia'])[2] | 
    self.driver.find_element(By.XPATH, "(//button[@id=\'selectedSocialMedia\'])[2]").click()
    # 12 | click | xpath=(//button[@id='selectedSocialMedia'])[3] | 
    self.driver.find_element(By.XPATH, "(//button[@id=\'selectedSocialMedia\'])[3]").click()
    # 13 | click | css=button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()
    # 14 | click | css=.sidebar-link:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-link:nth-child(1)").click()
  
