# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT4():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t4(self):
    # Test name: T4
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:5503/SElogin.html | 
    self.driver.get("http://127.0.0.1:5503/SElogin.html")
    # 2 | setWindowSize | 1050x590 | 
    self.driver.set_window_size(1050, 590)
    # 3 | click | linkText=Sign up | 
    self.driver.find_element(By.LINK_TEXT, "Sign up").click()
    # 4 | click | css=.userid | 
    self.driver.find_element(By.CSS_SELECTOR, ".userid").click()
    # 5 | type | css=.userid | samridddhkumar10@gmail.com
    self.driver.find_element(By.CSS_SELECTOR, ".userid").send_keys("samridddhkumar10@gmail.com")
    # 6 | click | css=div:nth-child(3) > .password | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > .password").click()
    # 7 | type | css=div:nth-child(3) > .password | sam
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > .password").send_keys("sam")
    # 8 | click | css=div:nth-child(4) > .password | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .password").click()
    # 9 | type | css=div:nth-child(4) > .password | abdgg
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > .password").send_keys("abdgg")
    # 10 | click | css=div:nth-child(5) > .password | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > .password").click()
    # 11 | type | css=div:nth-child(5) > .password | kjdni
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > .password").send_keys("kjdni")
    # 12 | click | css=.login-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".login-button").click()
    # 13 | click | css=.myprofile | 
    self.driver.find_element(By.CSS_SELECTOR, ".myprofile").click()
    # 14 | click | css=button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()
    # 15 | click | css=.sidebar-link:nth-child(3) > div | 
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-link:nth-child(3) > div").click()
    # 16 | click | css=.sidebar-link:nth-child(1) > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-link:nth-child(1) > img").click()
    # 17 | click | css=.thumbnail | 
    self.driver.find_element(By.CSS_SELECTOR, ".thumbnail").click()
  
