# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProjtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_projtest(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.LINK_TEXT, "IIITV Airport").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".footer__column:nth-child(2) > .footer__heading").click()
    self.driver.find_element(By.CSS_SELECTOR, ".footer__column:nth-child(2) > .footer__heading").click()
    self.driver.find_element(By.CSS_SELECTOR, ".footer__column:nth-child(1) > .footer__heading").click()
    self.driver.find_element(By.CSS_SELECTOR, ".footer__column:nth-child(3) > .footer__heading").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Careers").click()
    self.vars["win2346"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win2346"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.switch_to.window(self.vars["win2346"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.LINK_TEXT, "Login/Signup").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".nav-links > a").click()
    self.vars["win7789"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win7789"])
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("ABC")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("LMFAO")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
  
