# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1(self):
        self.driver.get("http://127.0.0.1:5501/index.html")
        self.driver.find_element(By.ID, "email").send_keys("honeykanna2024@gmail.com")
        self.driver.find_element(By.ID, "password").send_keys("Manikanta20@")
        self.driver.find_element(By.ID, "remember-me").click()
        self.driver.find_element(By.NAME, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "Forgot Password?").click()
        self.driver.find_element(By.ID, "email").send_keys("manikanta0224402@gmail.com")
        self.driver.find_element(By.NAME, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "Sign up now").click()
        google_login = self.driver.find_element(By.CSS_SELECTOR, ".loginBtn--google > img")
        google_login.click()
        self.driver.find_element(By.NAME, "username").send_keys("Manikanta20")
        self.driver.find_element(By.NAME, "email").send_keys("manikanta0224402@gmail.com")
        self.driver.find_element(By.NAME, "password").send_keys("Manikanta20@")
        self.driver.find_element(By.NAME, "confirm_password").send_keys("Manikanta20@")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        facebook_login = self.driver.find_element(By.CSS_SELECTOR, ".loginBtn--facebook > img")
        facebook_login.click()
        self.driver.find_element(By.NAME, "username").send_keys("202211050@diu.iiitvadodara.ac.in")
        self.driver.find_element(By.NAME, "password").send_keys("Manikanta20@")
        self.driver.find_element(By.NAME, "confirm_password").send_keys("Manikanta20@")
        self.driver.find_element(By.CSS_SELECTOR, "button").click()
        alert = self.driver.switch_to.alert
        alert_text = alert.text
        alert.accept()
        assert alert_text == "Registered successfully!"
