# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("http://127.0.0.1:5500/index.html")
    self.driver.set_window_size(801, 864)
    self.driver.find_element(By.ID, "top_book_now").click()
    self.driver.find_element(By.ID, "upi").click()
    self.driver.find_element(By.ID, "upi_Id").click()
    self.driver.find_element(By.ID, "upi_Id").send_keys("zorouchiha@upi")
    self.driver.find_element(By.ID, "pay_upi").click()
    self.driver.find_element(By.ID, "return_home").click()
  
