# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUPDATEEXISTINGSTUDENT():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uPDATEEXISTINGSTUDENT(self):
    self.driver.get("http://localhost:5173/courses")
    self.driver.set_window_size(1024, 816)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiPaper-root:nth-child(6) .MuiButtonBase-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiPaper-root:nth-child(6) .MuiButtonBase-root").click()
    self.driver.execute_script("window.scrollTo(0,147.1999969482422)")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiGrid-grid-lg-8 > div").click()
    self.driver.find_element(By.ID, ":r1:").send_keys("Prakhar Jain")
    self.driver.find_element(By.ID, ":r5:").click()
    self.driver.find_element(By.ID, ":r5:").click()
    self.driver.find_element(By.ID, ":r5:").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, ":r5:").send_keys("<-Jain Sahab->")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .MuiButtonBase-root").click()
    self.driver.close()
  
