# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestADDNEWSTUDENT():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aDDNEWSTUDENT(self):
    self.driver.get("http://localhost:5173/addcourse")
    self.driver.set_window_size(1024, 816)
    self.driver.find_element(By.ID, ":r1:").click()
    self.driver.find_element(By.ID, ":r1:").send_keys("Yatharth")
    self.driver.find_element(By.ID, ":r3:").click()
    self.driver.find_element(By.ID, ":r3:").send_keys("4th")
    self.driver.find_element(By.ID, ":r5:").click()
    self.driver.find_element(By.ID, ":r5:").send_keys("<-Yatharth->")
    self.driver.find_element(By.ID, ":r7:").click()
    self.driver.find_element(By.ID, ":r7:").send_keys("49000")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButton-sizeLarge").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .MuiButtonBase-root").click()
    self.driver.close()
  
