# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2MarketPlace():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2MarketPlace(self):
    self.driver.get("http://127.0.0.1:5501/login.html")
    self.driver.set_window_size(1722, 1082)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("foreversurya007@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("13536565fvv")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.LINK_TEXT, "Explore Now").click()
    self.driver.find_element(By.LINK_TEXT, "Market Place").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex > .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(7) .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(7) .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(8) .fa-solid").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-dark").click()
    assert self.driver.switch_to.alert.text == "Thank you for your purchase!!!"
    self.driver.close()
  
