# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest5ContactUs():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test5ContactUs(self):
    self.driver.get("http://127.0.0.1:5501/login.html")
    self.driver.set_window_size(1722, 1082)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("foreversurya007@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("2652f651ghbgfnm")
    self.driver.find_element(By.ID, "login").click()
    self.driver.find_element(By.LINK_TEXT, "Explore Now").click()
    self.driver.find_element(By.LINK_TEXT, "Contact Us").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("foreversurya007@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.close()
  
