# Generated by Selenium IDE
import pytest
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By


driver = webdriver.Chrome()
vars = {}

  
driver.get("http://localhost:5173/")
driver.set_window_size(1552, 832)
driver.find_element(By.CSS_SELECTOR, ".bg-gray-200:nth-child(1)").click()
driver.find_element(By.CSS_SELECTOR, ".bg-gray-200:nth-child(1)").send_keys("user")
driver.find_element(By.CSS_SELECTOR, ".bg-gray-200:nth-child(2)").send_keys("user")
driver.find_element(By.CSS_SELECTOR, ".font-bold:nth-child(3)").click()
# sleep(2)
driver.find_element(By.CSS_SELECTOR, ".bg-gray-200").send_keys("arti")
driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(1) > .block").click()
assert driver.switch_to.alert.text == "Are you sure you want to issue Artificial Intelligence – A Modern Approach?"
driver.switch_to.alert.accept()
assert driver.switch_to.alert.text == "Book issued successfully"
  
