# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBucketlist():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bucketlist(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.CSS_SELECTOR, ".\\_ctaLink_190ou_55").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_ctaLink_190ou_55")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\_btn_qgcjy_1").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("bhavnagar")
    self.driver.find_element(By.CSS_SELECTOR, ".\\_sidebar_1embv_1 button").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
  
