# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCalender():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_calender(self):
    self.driver.get("http://127.0.0.1:5501/index.html")
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.CSS_SELECTOR, "#calendar-tab > span").click()
    self.driver.find_element(By.ID, "nav-toggle-layer").click()
    self.driver.find_element(By.CSS_SELECTOR, ".calendar-cell:nth-child(18)").click()
    self.driver.find_element(By.ID, "add-event-btn").click()
    self.driver.find_element(By.ID, "event-name").click()
    self.driver.find_element(By.ID, "event-name").send_keys("Eggs")
    self.driver.find_element(By.ID, "event-date").click()
    self.driver.find_element(By.ID, "event-date").click()
    self.driver.find_element(By.ID, "event-date").send_keys("2024-04-09")
    self.driver.find_element(By.ID, "event-start-time").click()
    self.driver.find_element(By.ID, "event-start-time").click()
    self.driver.find_element(By.ID, "event-start-time").click()
    self.driver.find_element(By.ID, "event-start-time").click()
    self.driver.find_element(By.ID, "event-start-time").click()
    self.driver.find_element(By.ID, "event-start-time").send_keys("10:56")
    self.driver.find_element(By.ID, "event-end-time").click()
    self.driver.find_element(By.ID, "event-end-time").click()
    self.driver.find_element(By.ID, "event-end-time").send_keys("00:59")
    self.driver.find_element(By.CSS_SELECTOR, "#event-form-data > label:nth-child(9)").click()
    self.driver.find_element(By.ID, "event-notes").click()
    self.driver.find_element(By.ID, "event-notes").send_keys("Watch")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(13)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(13)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".calendar-cell:nth-child(40)").click()
    self.driver.find_element(By.ID, "next-month-btn").click()
    self.driver.find_element(By.ID, "next-month-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    self.driver.find_element(By.ID, "next-month-btn").click()
  
