# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestToDoList():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_toDoList(self):
    self.driver.get("http://127.0.0.1:5500/index.html")
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.CSS_SELECTOR, "#todo-list-tab > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-header > button").click()
    self.driver.find_element(By.ID, "new-task-input").click()
    self.driver.find_element(By.ID, "new-task-input").send_keys("Medicine")
    self.driver.find_element(By.ID, "task-location").click()
    dropdown = self.driver.find_element(By.ID, "task-location")
    dropdown.find_element(By.XPATH, "//option[. = 'Outdoor']").click()
    self.driver.find_element(By.ID, "new-task-submit").click()
    element = self.driver.find_element(By.ID, "new-task-submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "new-task-input").click()
    self.driver.find_element(By.ID, "new-task-input").send_keys("Egg")
    self.driver.find_element(By.ID, "new-task-submit").click()
    element = self.driver.find_element(By.ID, "new-task-submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "new-task-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".task-item:nth-child(2) > .delete-task-btn").click()
  
