# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignIn():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signIn(self):
    self.driver.get("http://127.0.0.1:5501/signup.html")
    self.driver.set_window_size(1200, 741)
    self.driver.find_element(By.ID, "fullname").click()
    self.driver.find_element(By.ID, "fullname").send_keys("tanuj")
    self.driver.find_element(By.ID, "signup_email").click()
    self.driver.find_element(By.ID, "signup_email").send_keys("tanuj@gmail.com")
    self.driver.find_element(By.ID, "signup_password").click()
    self.driver.find_element(By.ID, "signup_password").send_keys("123456")
    self.driver.find_element(By.ID, "confirm_password").click()
    self.driver.find_element(By.ID, "confirm_password").send_keys("123456")
    self.driver.find_element(By.ID, "signupSubmit").click()
    assert self.driver.switch_to.alert.text == "Firebase: Error (auth/email-already-in-use)."
  
