# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAlarm():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_alarm(self):
    self.driver.get("http://127.0.0.1:5501/index.html")
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.CSS_SELECTOR, "#alarm-tab > span").click()
    self.driver.find_element(By.ID, "nav-toggle-layer").click()
    self.driver.find_element(By.ID, "alarmTimeInput").click()
    self.driver.find_element(By.ID, "alarmTimeInput").click()
    self.driver.find_element(By.ID, "alarmTimeInput").send_keys("10:54")
    self.driver.find_element(By.ID, "alarmNotesInput").click()
    self.driver.find_element(By.ID, "alarmNotesInput").send_keys("Eggs")
    self.driver.find_element(By.CSS_SELECTOR, ".alarmModal-saveBtn").click()
  
