# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStopWatch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_stopWatch(self):
    self.driver.get("http://127.0.0.1:5501/index.html")
    self.driver.set_window_size(1440, 900)
    self.driver.find_element(By.CSS_SELECTOR, "#stopwatch-tab > span").click()
    self.driver.find_element(By.ID, "nav-toggle-layer").click()
    self.driver.find_element(By.CSS_SELECTOR, ".stopwatchClock").click()
    self.driver.find_element(By.CSS_SELECTOR, ".stopwatchStartStopBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".stopwatchStartStopBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".stopwatchResetBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".stopwatchStartStopBtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".stopwatchResetBtn").click()
  
