# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
#/*class TestAddAuction():
 # def setup_method(self, method):
  #  self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    #self.vars = {}
  
  #def teardown_method(self, method):
   #3 self.driver.quit()
 # def test_addAuction(self):
driver = webdriver.Chrome()
driver.get("http://localhost:3000/")
driver.set_window_size(1552, 832)
driver.find_element(By.LINK_TEXT, "My Auctions").click()
driver.find_element(By.NAME, "name").click()
driver.find_element(By.NAME, "name").send_keys("Cooler")
driver.find_element(By.NAME, "category").click()
driver.find_element(By.NAME, "category").send_keys("Electronics") 
driver.find_element(By.CSS_SELECTOR, ".formInput:nth-child(4) > input").click()
driver.find_element(By.CSS_SELECTOR, ".formInput:nth-child(4) > input").send_keys("very cool")
driver.find_element(By.NAME, "startTime").click()
driver.find_element(By.NAME, "startTime").send_keys("2024-04-14")
driver.find_element(By.NAME, "endTime").click()
driver.find_element(By.NAME, "endTime").send_keys("2024-04-17") 
driver.find_element(By.NAME, "imageUrl").click()
driver.find_element(By.NAME, "imageUrl").send_keys("https://images.pexels.com/photos/2923672/pexels-photo-2923672.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
driver.find_element(By.CSS_SELECTOR, "button:nth-child(8)").click()
driver.quit()
  
