# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://localhost:3000/auth")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("uvyadav04")
    self.driver.find_element(By.NAME, "password").send_keys("12345")
    self.driver.find_element(By.CSS_SELECTOR, ".fs-5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".user-profile > .d-inline").click()
    self.driver.find_element(By.LINK_TEXT, "New user").click()
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("Dinesh Yadav")
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-4 > .my-md-3:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-4 > .my-md-3:nth-child(3)").send_keys("uvyadav07")
    self.driver.find_element(By.NAME, "email").send_keys("uvyadav2230@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".my-md-3:nth-child(5)").send_keys("12345")
    self.driver.find_element(By.CSS_SELECTOR, ".mt-4").click()
  
