# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("http://localhost:3000/home")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.LINK_TEXT, "treatment").click()
    element = self.driver.find_element(By.LINK_TEXT, "treatment")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-5").send_keys("all")
    self.driver.find_element(By.CSS_SELECTOR, ".my-2").click()
    self.driver.find_element(By.LINK_TEXT, "treatment").click()
    self.driver.find_element(By.CSS_SELECTOR, ".treat").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-5").send_keys("ra")
    self.driver.find_element(By.CSS_SELECTOR, ".my-2:nth-child(4)").click()
  
