# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test4(self):
    self.driver.get("http://localhost:3000/home")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.LINK_TEXT, "Fitness").click()
    element = self.driver.find_element(By.LINK_TEXT, "Fitness")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".beginner > .me-5:nth-child(1) > .opacity-50:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Fitness").click()
    self.driver.find_element(By.CSS_SELECTOR, ".beginner > .me-5:nth-child(4) > .opacity-50:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "Fitness").click()
    self.driver.find_element(By.CSS_SELECTOR, ".intermediate > .me-5:nth-child(1) > .opacity-50:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.LINK_TEXT, "Fitness").click()
    self.driver.find_element(By.CSS_SELECTOR, ".intermediate > .me-5:nth-child(5) > .opacity-50:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
