# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest5():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test5(self):
    self.driver.get("http://127.0.0.1:5501/Home/index.html")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Admin Portal").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").click()
    element = self.driver.find_element(By.ID, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "startElectionBtn").click()
    self.driver.find_element(By.ID, "seeAllVotersBtn").click()
    self.driver.find_element(By.ID, "verifyVoterBtn").click()
    self.driver.find_element(By.ID, "displayCandidateBtn").click()
    self.driver.find_element(By.ID, "setDeadlineBtn").click()
    self.driver.find_element(By.ID, "deadlineDateTime").click()
    self.driver.find_element(By.ID, "deadlineDateTime").send_keys("2024-04-16T22:12")
    self.driver.find_element(By.ID, "setDeadlineTimeBtn").click()
    self.driver.find_element(By.ID, "giveResultBtn").click()
    self.driver.find_element(By.ID, "sendSMSBtn").click()
    self.driver.find_element(By.ID, "sendEmailBtn").click()
    self.driver.find_element(By.LINK_TEXT, "Home Page →").click()
    self.driver.find_element(By.LINK_TEXT, "Contact us").click()
  
