# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test3(self):
    self.driver.get("http://127.0.0.1:5501/Home/index.html")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".forms li:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "New registration for general electors").click()
    self.driver.find_element(By.LINK_TEXT, "Vote Now").click()
    self.driver.find_element(By.ID, "president").click()
    dropdown = self.driver.find_element(By.ID, "president")
    dropdown.find_element(By.XPATH, "//option[. = 'Candidate 2']").click()
    self.driver.find_element(By.ID, "voting-form").click()
    dropdown = self.driver.find_element(By.ID, "vice-president")
    dropdown.find_element(By.XPATH, "//option[. = 'Candidate 4']").click()
    element = self.driver.find_element(By.ID, "vice-president")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "vice-president")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "vice-president")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
