// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TEST2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TEST2', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css("li:nth-child(4) > span")).click()
    await driver.findElement(By.name("title")).click()
    await driver.findElement(By.name("title")).sendKeys("day 1")
    await driver.findElement(By.name("amount")).click()
    await driver.findElement(By.name("amount")).sendKeys("10000")
    await driver.findElement(By.id("date")).click()
    await driver.findElement(By.css(".react-datepicker__day--018")).click()
    await driver.findElement(By.id("category")).click()
    {
      const dropdown = await driver.findElement(By.id("category"))
      await dropdown.findElement(By.xpath("//option[. = 'Clothing']")).click()
    }
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("no!")
    await driver.findElement(By.css(".sc-gKPRtg")).click()
  })
})
