# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGiveloan():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_giveloan(self):
    self.driver.get("http://localhost/Cooldudes_Bank/")
    self.driver.set_window_size(1178, 824)
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(5) > button").click()
    self.driver.find_element(By.ID, "select").click()
    dropdown = self.driver.find_element(By.ID, "select")
    dropdown.find_element(By.XPATH, "//option[. = 'virat (CURRENT BALANCE : 5000 )']").click()
    self.driver.find_element(By.NAME, "loan").click()
    self.driver.find_element(By.NAME, "loan").send_keys("5000")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(5) > button").click()
    self.driver.find_element(By.ID, "select").click()
    dropdown = self.driver.find_element(By.ID, "select")
    dropdown.find_element(By.XPATH, "//option[. = 'virat (CURRENT BALANCE : 10000 )']").click()
    self.driver.find_element(By.NAME, "loan").click()
    self.driver.find_element(By.NAME, "loan").send_keys("-1000")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".loanprocess").click()
    self.driver.find_element(By.NAME, "loan").click()
  
