# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC1(self):
    self.driver.get("https://tapshare.xyz/")
    self.driver.set_window_size(713, 738)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-add-code").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-add-code")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("SAMPLE FILE")
    self.driver.find_element(By.NAME, "text").send_keys("HELLO THERE , MYSELF URVISH")
    self.driver.find_element(By.CSS_SELECTOR, ".h-\\[100px\\]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-red-500").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".flex > .text-white").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".flex > .text-white")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.NAME, "code").send_keys("HELLO 1234")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-red-500").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-\\[1rem\\]").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiChip-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-10:nth-child(1) .inline-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-200").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-200 > .text-2xl").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-red-500").click()
    self.driver.close()
  
