// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC 1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC 1', async function() {
    await driver.get("https://tapshare.xyz/")
    await driver.manage().window().setRect({ width: 713, height: 738 })
    await driver.findElement(By.css(".btn-add-code")).click()
    {
      const element = await driver.findElement(By.css(".btn-add-code"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.name("title")).click()
    await driver.findElement(By.name("title")).sendKeys("SAMPLE FILE")
    await driver.findElement(By.name("text")).sendKeys("HELLO THERE , MYSELF URVISH")
    await driver.findElement(By.css(".h-\\[100px\\]")).click()
    await driver.findElement(By.css(".bg-blue-500")).click()
    await driver.findElement(By.css(".bg-blue-500")).click()
    {
      const element = await driver.findElement(By.css(".bg-blue-500"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".bg-red-500")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".flex > .text-white")).click()
    {
      const element = await driver.findElement(By.css(".flex > .text-white"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.name("code")).sendKeys("HELLO 1234")
    await driver.findElement(By.css(".bg-blue-500")).click()
    {
      const element = await driver.findElement(By.css(".bg-blue-500"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".gap-1")).click()
    await driver.findElement(By.css(".bg-red-500")).click()
    await driver.findElement(By.css(".text-\\[1rem\\]")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(3) > .MuiChip-label")).click()
    await driver.findElement(By.css(".mb-10:nth-child(1) .inline-flex")).click()
    await driver.findElement(By.css(".p-0")).click()
    await driver.findElement(By.css(".bg-gray-200")).click()
    await driver.findElement(By.css(".bg-gray-200 > .text-2xl")).click()
    await driver.findElement(By.css(".bg-red-500")).click()
    await driver.close()
  })
})
