# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestShareTextFile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_shareTextFile(self):
    self.driver.get("https://tapshare.xyz/")
    self.driver.set_window_size(697, 738)
    self.driver.find_element(By.CSS_SELECTOR, ".w-6").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("Hi SAMPLE TEXT HEADING")
    self.driver.find_element(By.NAME, "text").send_keys("Hello\\nMy\\nName \\nis \\nURVISH JOSHI ")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-500").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.ID, "standard-select-currency")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-50:nth-child(3) .hidden").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-50:nth-child(4) > .px-3:nth-child(2) > .flex > .flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".px-3:nth-child(3) .hidden").click()
    self.driver.find_element(By.CSS_SELECTOR, ".px-3:nth-child(4) > .flex > .flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".px-3:nth-child(5) > .flex > .flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-gray-100:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-3xl > path").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".text-3xl > path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiBackdrop-root").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-blue-500").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "path:nth-child(4)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.LINK_TEXT, "?")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiChip-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-10:nth-child(1) .inline-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3Atext-gray-50").click()
    self.driver.close()
  
